name: baby_f_words
description: Baby First Words

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.3.0+5 #+4 erased this +4 it seemed to read to google play as the main version number

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.4
  audioplayers: ^5.2.0
  flutter_custom_clippers: ^2.1.0
  google_mobile_ads: ^3.0.0
  path_provider: ^2.1.1
  http: ^0.13.0
  liquid_progress_indicator: ^0.4.0
  recase: ^4.1.0
  logger: ^2.0.2
  equatable: ^2.0.5


  #Firebase Dependencies
  firebase_core: ^2.17.0
  firebase: ^9.0.3
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3  #https://pub.dev/packages/cloud_firestore/install
  firebase_storage: ^11.4.0
  firebase_analytics_web: ^0.5.5 #https://pub.dev/packages/firebase_analytics/install
  firebase_analytics: ^10.5.0

  #Sound
  #flutter_sound: ^9.2.13 #Using this to test if it plays throuh iphone's speakers, as audio_players is not doing that on iphone, but works marvellously in android

  #State Management
  provider: ^6.0.5
  get_it: ^7.6.4

  #animations:
  lottie: ^2.6.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.1
  firebase_app_check: ^0.2.1+2


dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
    - assets/
    - assets/music/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
